-- select database
use movies;

-- creating table
CREATE TABLE IF NOT EXISTS TELUGUMOVIES(
	ID INT,
    MOVIENAME VARCHAR(30),
    DIRECTOR VARCHAR(30),
    DURATION int
);

--  CHECK TABLE DESCRIPTION
-- SYNTAX: DESCRIBE TableName;
DESCRIBE TELUGUMOVIES;