create database school;

-- SELECT DATABASE
USE SCHOOL;
-- students table
CREATE TABLE STUDENTS(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL,
    GENDER VARCHAR(10),
    CLASS INT
);
DESCRIBE STUDENTS;

-- ALTER COMMAND OPERATIONS
-- ADD NEW AGE COLUMN
-- SYNTAX: ALTER TABLE TableName ADD COLUMN ColName Datatype [CONSTRAINT];
-- ADD DATE_OF_BIRTH COLUMN
ALTER TABLE STUDENTS ADD COLUMN AGE TINYINT CHECK(AGE > 5);
ALTER TABLE STUDENTS ADD COLUMN DATE_OF_BIRTH DATE;

ALTER TABLE STUDENTS ADD COLUMN LOCATION VARCHAR(50),
						ADD COLUMN ADDRESS varchar(30);
DESCRIBE STUDENTS;

-- DELETE COLUMNS
-- SYNTAX: ALTER TABLE TableName DROP COLUMN ColName;
-- DELETE LOCATION AND ADDRESS COLUMNS
ALTER TABLE STUDENTS DROP COLUMN LOCATION, DROP COLUMN ADDRESS;

-- CHANGE ID COLUMN NAME TO STDID 
ALTER TABLE STUDENTS RENAME COLUMN ID TO STDID;

DESCRIBE STUDENTS;

-- CHANGE GENDER COLUMN DATATYPE
-- SYNTAX: ALTER TABLE TableName MODIFY COLUMN Colname DATATYPE [CONSTRINT];
ALTER TABLE STUDENTS MODIFY COLUMN GENDER ENUM('MALE','FEMALE');
describe STUDENTS;
-- CONVERT CLASS DATATYPE INTO TINYINT
ALTER TABLE STUDENTS MODIFY COLUMN CLASS TINYINT UNSIGNED;

DESC STUDENTS;

-- UPDATE CLASS AS NOT NULL
ALTER TABLE STUDENTS MODIFY COLUMN CLASS TINYINT UNSIGNED NOT NULL;









