use school;

select * from students;

-- select 8class students data
select * from students
where class = 8;

-- get the students data based on class
DELIMITER //
CREATE PROCEDURE GET_STUDENTS_BY_CLASS(IN CLASS_NO INT)
BEGIN
	SELECT * FROM STUDENTS
    WHERE CLASS = CLASS_NO;
END //
DELIMITER ;

-- CALL STORED PROCEDURE
CALL GET_STUDENTS_BY_CLASS(6);
CALL GET_STUDENTS_BY_CLASS(7);
CALL GET_STUDENTS_BY_CLASS(8);

-- GET THE CLASS STUDENTS COUNT
DELIMITER //
CREATE PROCEDURE GET_CLASS_COUNT(IN CLASS_NO INT,
									OUT TOTAL_COUNT INT)
BEGIN
	SELECT COUNT(*) INTO TOTAL_COUNT FROM STUDENTS
    WHERE CLASS = CLASS_NO;
END //
DELIMITER ;

-- DEFINE VARIABLE
SET @COUNT = 0;
CALL GET_CLASS_COUNT(7,@COUNT);
SELECT @COUNT;








