create database tips_analysis;

use tips_analysis;

select * from tips;
desc tips;

-- change SEX column name as GENDER 
ALTER TABLE TIPS RENAME COLUMN SEX TO GENDER;
SELECT * FROM TIPS;
-- 1. GET FEMALE RECORDS
SELECT * FROM TIPS 
WHERE GENDER = 'FEMALE';

-- 2. FIND MALE RECORDS
SELECT * FROM TIPS 
WHERE GENDER = 'MALE';
-- 3. FIND DINNER TIME FEMALE RECORDS
SELECT * FROM TIPS 
WHERE GENDER = 'FEMALE' AND TIME = 'DINNER';
-- 4. FIND THE SIZE 2 RECORDS
SELECT * FROM TIPS 
WHERE SIZE = 2;
-- 5. FIND MALE SMOKER RECORDS
SELECT * FROM TIPS 
WHERE GENDER = 'MALE'AND SMOKER = 'YES';
-- 6. GET THE NON-SMOKER FEMALE RECORDS
SELECT * FROM TIPS 
WHERE GENDER = 'FEMALE' AND SMOKER = 'NO';
-- 7. GET THE DINNER TIME MALE RECORDS
SELECT * FROM TIPS 
WHERE GENDER = 'MALE' AND TIME='DINNER';
-- 8. GET THE FEMALE RECORDS IN DESCENDING ORDER AS PER THE TOTAL_BILL
SELECT * FROM TIPS 
WHERE GENDER = 'FEMALE'
ORDER BY TOTAL_BILL DESC;

-- 9. GET THE TOP 5 MALE TOTAL_BILLS 
SELECT * FROM TIPS 
WHERE GENDER = 'MALE'
ORDER BY TOTAL_BILL DESC
LIMIT 5;
-- 10. GET BOTH SIZE 2 AND 3 RECORDS
SELECT * FROM TIPS 
WHERE SIZE = 2 OR SIZE = 3;
-- 11. GET THE RECORDS WHOSE TOTAL BILL IN THE REANGE OF 10 TO 20
SELECT * FROM TIPS 
WHERE TOTAL_BILL >= 10 AND TOTAL_BILL <= 20;

SELECT * FROM TIPS 
WHERE TOTAL_BILL BETWEEN 10 AND 20;
-- 12 GET SIZE 2,3 AND 4 RECORDS
SELECT * FROM TIPS 
WHERE SIZE = 2 OR SIZE = 3 OR SIZE = 4;

SELECT * FROM TIPS 
WHERE SIZE IN (2,3,4);

-- 13. SECOND HIGHEST TOTAL BILL RECORD
SELECT * FROM TIPS 
ORDER BY TOTAL_BILL DESC
LIMIT 1 OFFSET 1;



--  14. RETURN TOTAL RECORDS IN TIPS TABLE 
SELECT COUNT(*) FROM TIPS;
-- 15.  RETURN TOTAL MELE SMOKER COUNT
SELECT COUNT(*) FROM TIPS
WHERE GENDER = 'MALE' AND SMOKER ='YES';
-- 16.  RETURN TOTAL TIP
SELECT SUM(TIP) FROM TIPS;
-- 17.  RETURN FEMALE NON SMOKER COUNT
SELECT COUNT(*) FROM TIPS
WHERE GENDER = 'FEMALE' AND SMOKER ='NO';
-- 18.  RETURN MINIMUM AND MAXIMUM TOTAL BILL
SELECT MIN(TOTAL_BILL), MAX(TOTAL_BILL) FROM TIPS;



-- GROUP BY QUERIES
-- 19. GET THE GENDER COLUMN UNIQUE VALUES
SELECT DISTINCT GENDER FROM TIPS;
SELECT GENDER FROM TIPS 
GROUP BY GENDER;
-- 20. GET THE DINNER TIME RECORDS COUNT
-- 21. GET THE TOTAL RECORS COUNT AS PER THE GENDER COLUMN
SELECT GENDER, COUNT(*) FROM tips
GROUP BY GENDER;
-- 22. GET THE SMOKER AND NON-SMOKER COUNT
SELECT SMOKER, COUNT(*) AS TOTAL_COUNT FROM tips
GROUP BY SMOKER;
-- 23. GET THE SUNDAY TOTAL RECORDS AS PER THE GENDER
SELECT DAY,GENDER, COUNT(*) AS TOTAL_COUNT FROM tips
WHERE DAY = 'SUN'
GROUP BY GENDER;
-- 24. GET THE SIZE 2'S TOTAL COUNT AS PER THE GENDER
SELECT SIZE, GENDER, COUNT(*) AS TOTAL_COUNT FROM tips
WHERE SIZE = 2
GROUP BY GENDER;
-- 25. GET THE EACH SIZE COUNT IN DESCENDING ORDER
SELECT SIZE, COUNT(*) AS TOTAL_COUNT FROM tips
GROUP BY SIZE
ORDER BY TOTAL_COUNT DESC;
-- 26. GET THE SIZE 2, 3, AND 4 SOMKER AND NON-SMOKER COUNT
SELECT SMOKER, COUNT(*) AS TOTAL_COUNT FROM tips
WHERE SIZE IN (2,3,4)
GROUP BY SMOKER;
-- 27. GET THE EACH SIZE COUNT AS PER THE GENDER
SELECT SIZE, GENDER, COUNT(*) AS TOTAL_COUNT FROM tips
GROUP BY SIZE, GENDER
ORDER BY SIZE ASC, TOTAL_COUNT DESC;
-- 28. FIND THE EACH SIZE MAXIMUM AND MINIMUM TOTAL_BILL
SELECT SIZE, MIN(TOTAL_BILL), MAX(TOTAL_BILL) FROM TIPS
GROUP BY SIZE;
-- 29. FIND THE MALE TOTAL RECORDS IN DESCNDING ORDER AS PERTHE DAY 
SELECT DAY, COUNT(*) AS TOTAL_COUNT FROM TIPS 
WHERE GENDER = 'MALE'
GROUP BY DAY 
ORDER BY TOTAL_COUNT DESC;

-- 30. FIND TOTAL RECORDS AS PER THE SIZE
SELECT SIZE, COUNT(*) AS TOTAL_COUNT FROM TIPS 
GROUP BY SIZE;


--  31. RETURN THE SIZE WHICH ONE TOTAL COUNT IS MORETHAN 30
SELECT SIZE, COUNT(*) AS TOTAL_COUNT FROM TIPS 
GROUP BY SIZE
HAVING TOTAL_COUNT > 30;

-- 32. GET THE EACH SIZE GENDER COUNT WHICH IS MORETHAN 20
-- 33. GET THE SIZES WHICH IS MAXIMUM TOTAL_BILL AND MINIMUM TOTAL_BILL
-- 										DIFFERENCE IS LESSERTHEN 30
SELECT SIZE, MAX(TOTAL_BILL),
			MIN(TOTAL_BILL), 
            (MAX(TOTAL_BILL)- MIN(TOTAL_BILL)) 
FROM TIPS 
GROUP BY SIZE
HAVING MAX(TOTAL_BILL) - MIN(TOTAL_BILL) < 30;			








SELECT GENDER, SMOKER, COUNT(*) FROM TIPS
WHERE GENDER = 'FEMALE' AND SMOKER ='NO';




