USE BANK;
SELECT * FROM ACCOUNTS;

CREATE TABLE TRANSCATIONS(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    ACCOUNT INT, 
    TYPE ENUM('DEBIT', 'CREDIT'),
    AMOUNT INT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- CREATE TRIGGER AFTER_TRANSCATION_TRIGGER
DELIMITER //
CREATE TRIGGER AFTER_TRANSCATION_TRIGGER
AFTER UPDATE
ON ACCOUNTS
FOR EACH ROW
BEGIN
	INSERT INTO TRANSCATIONS(ACCOUNT, TYPE, AMOUNT)
    VALUES(OLD.ID, 
		IF(OLD.AMOUNT > NEW.AMOUNT, "DEBIT", "CREDIT"), 
		ABS(OLD.AMOUNT - NEW.AMOUNT)
        );
END //
DELIMITER ;

SELECT * FROM ACCOUNTS;
-- NOW DEBIT 2000 FROM 1001 ACCOUNT
UPDATE ACCOUNTS SET AMOUNT = AMOUNT -2000
WHERE ID = 1001;

SELECT * FROM TRANSCATIONS;







    